name: Compile IconSvg.dylib

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Xcode CLI Tools
        run: |
          sudo xcode-select --reset
          sudo xcode-select --install

      - name: Compile
        run: |
          # 获取 iOS SDK 路径
          SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          # 编译
          clang -isysroot $SDK_PATH -shared -framework UIKit -fobjc-arc IconSvg.m -o IconSvg.dylib
          # 签名
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_arm64
          chmod +x ldid_macosx_arm64
          ./ldid_macosx_arm64 -S IconSvg.dylib
          # 打包
          zip IconSvg.zip IconSvg.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: IconSvg-Plugin
          path: IconSvg.zip
